### ISSUE TITLE
Error: Cannot find module 'aws-valkyrie-utils'

### ISSUE THREAD

**Issue by tiero** [giowe/aws-valkyrie-cli#15]
Having `aws-valkyrie-cli@0.13` and `npm@5.6.0` and `node@9.11.1` after install, launching a command it throws 

```
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'aws-valkyrie-utils'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/tiero/.nvm/versions/node/v9.11.1/lib/node_modules/aws-valkyrie-cli/commands/help.js:1:85)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by nicofuccella** [comment]
0.14.0 version has been published. 
It should fix this error.
